### ISSUE TITLE
add sites and data from Bargain Chemists

### ISSUE THREAD

**Issue by waltzaround** [CovidEngine/vaxxnz#26] opened 2021-09-06 07:19 UTC
As a vaxx user
I want to see ways to get vaxxed at Bargain Chemists
So that I can get vaccinated, and be less affected by COVID

This covers scraping the bargain chemists, and storing the results somewhere https://www.bargainchemist.co.nz/pages/covid-19-vaccination

**Comment by oeed** [comment] 2021-09-08 06:20
Duplicate of #27

**Closed by oeed** 2021-09-08 06:20 UTC
